import fs from 'fs';
import path from 'path';

const localesDir = path.join(process.cwd(), 'src', 'locales');

const translations = {
  en: {
    legal: {
      aboutTitle: "About Mythos Draft",
      aboutDesc: "The premier drafting tool for the Age of Mythology: Retold community.",
      aboutProject: "The Project",
      aboutProjectDesc: "Mythos Draft was created out of passion for the competitive Age of Mythology scene. It provides a real-time, synchronized environment for tournament organizers and players to conduct fair, structured map and god drafts before diving into the game.",
      aboutCreator: "The Creator",
      aboutCreatorDesc: "Developed and maintained by <strong class='text-white'>Kamarts</strong>. This project relies heavily on community feedback and active participation from the competitive player base.",
      aboutMission: "Our Mission",
      aboutMissionDesc: "Our goal is to elevate the competitive experience of Age of Mythology: Retold by providing a flawless, professional-grade infrastructure for drafting. We believe that a strong competitive scene needs robust tools, and Mythos Draft is our contribution to the community we love.",
      aboutDonate: "Support the Development",
      aboutDonateDesc: "Server hosting and database costs add up. If you love the app and want to help keep it ad-free and lightning fast, consider supporting the project.",
      aboutDonateBtn: "Donate Now",
      aboutContact: "Contact: goldpentakill@gmail.com",
      
      termsTitle: "Terms of Service",
      termsDesc: "Please read these terms carefully before using Mythos Draft.",
      termsUpdated: "Last Updated: October 2023",
      termsSec1Title: "1. Acceptance of Terms",
      termsSec1Desc: "By accessing and using Mythos Draft, you accept and agree to be bound by the terms and provision of this agreement.",
      termsSec2Title: "2. Fair Use & Intellectual Property",
      termsSec2Desc: "Mythos Draft is a fan-made, non-profit community tool. Age of Mythology: Retold and all related assets, characters, and names are the intellectual property of Microsoft Corporation. This tool claims no ownership over these assets and is provided under fair use for the benefit of the competitive community.",
      termsSec3Title: "3. User Conduct",
      termsSec3Desc: "Users agree to use the service respectfully. Abuse of the drafting system, intentional disruption of public lobbies, or exploitation of bugs may result in a ban from the platform.",
      termsSec4Title: "4. Service Availability",
      termsSec4Desc: "We strive for 100% uptime, especially during major tournaments, but Mythos Draft is provided \"as is\" without warranties of any kind. We reserve the right to modify or discontinue the service at any time.",
      termsSec5Title: "5. Third-Party Integrations",
      termsSec5Desc: "Our service utilizes Discord for authentication during official tournaments (Forja de Hefesto). By using these features, you also agree to Discord's Terms of Service.",

      privacyTitle: "Privacy Policy",
      privacyDesc: "How we collect, use, and protect your data.",
      privacyUpdated: "Last Updated: October 2023",
      privacySec1Title: "1. Data Collection",
      privacySec1Desc: "Mythos Draft collects minimal personal data. For standard lobbies, we only store temporary session IDs (Guest IDs) in your browser. No personal identifiable information is required to use the core drafting tool.",
      privacySec2Title: "2. Discord Authentication",
      privacySec2Desc: "For official tournament features (e.g., Forja de Hefesto), we use Discord OAuth. We only request your Discord ID, username, and avatar to verify your identity for the tournament. We do not have access to your private messages, email, or friends list.",
      privacySec3Title: "3. Firebase & Database",
      privacySec3Desc: "Our real-time infrastructure is powered by Google Firebase. Draft data, including player names and picks, are temporarily stored to facilitate the live sync. Completed drafts may be archived for statistical purposes.",
      privacySec4Title: "4. Data Sharing",
      privacySec4Desc: "We do not sell, trade, or rent your personal identification information to others. Draft statistics and meta data may be shared publicly, but this data is anonymized.",
      privacySec5Title: "5. Your Rights",
      privacySec5Desc: "You can clear your local storage at any time to remove your Guest ID. If you used Discord OAuth, you can revoke access to Mythos Draft from your Discord Authorized Apps settings.",

      cookiesTitle: "Cookie Policy",
      cookiesDesc: "Understanding how we use local storage to enhance your experience.",
      cookiesUpdated: "Last Updated: October 2023",
      cookiesSec1Title: "1. What are Cookies?",
      cookiesSec1Desc: "Cookies and Local Storage are small pieces of data stored on your device that help websites remember information about your visit. Mythos Draft relies primarily on Local Storage rather than traditional cookies.",
      cookiesSec2Title: "2. Essential Storage",
      cookiesSec2Desc: "We use strictly necessary Local Storage to manage your session. This includes storing a generated `guestId` so the server recognizes you if you accidentally refresh the page during an active draft. Without this, the drafting tool would break upon refresh.",
      cookiesSec3Title: "3. Preferences",
      cookiesSec3Desc: "We may also store simple preferences locally, such as your selected language or whether you have acknowledged our policies.",
      cookiesSec4Title: "4. Third-Party Tracking",
      cookiesSec4Desc: "We do not use invasive third-party tracking cookies (like Google Analytics or Meta Pixel) for advertising purposes. Your activity on Mythos Draft is not tracked for targeted ads.",

      consentTitle: "We value your privacy",
      consentDesc: "We use strictly necessary local storage to ensure the drafting tool functions properly and to recognize your session. We do not use advertising or tracking cookies. By continuing to use Mythos Draft, you consent to our use of essential local storage.",
      consentLearnMore: "Learn More",
      consentAccept: "Accept",
      backToHome: "Back to Home"
    }
  },
  pt: {
    legal: {
      aboutTitle: "Sobre o Mythos Draft",
      aboutDesc: "A principal ferramenta de draft para a comunidade de Age of Mythology: Retold.",
      aboutProject: "O Projeto",
      aboutProjectDesc: "O Mythos Draft foi criado por paixão ao cenário competitivo de Age of Mythology. Ele fornece um ambiente em tempo real e sincronizado para organizadores de torneios e jogadores realizarem drafts justos de mapas e deuses antes de entrarem no jogo.",
      aboutCreator: "O Criador",
      aboutCreatorDesc: "Desenvolvido e mantido por <strong class='text-white'>Kamarts</strong>. Este projeto depende fortemente do feedback da comunidade e da participação ativa dos jogadores competitivos.",
      aboutMission: "Nossa Missão",
      aboutMissionDesc: "Nosso objetivo é elevar a experiência competitiva de Age of Mythology: Retold fornecendo uma infraestrutura impecável e profissional para drafts. Acreditamos que um cenário competitivo forte precisa de ferramentas robustas, e o Mythos Draft é a nossa contribuição para a comunidade que amamos.",
      aboutDonate: "Apoie o Desenvolvimento",
      aboutDonateDesc: "Os custos de hospedagem de servidor e banco de dados se acumulam. Se você gosta do aplicativo e quer ajudar a mantê-lo sem anúncios e extremamente rápido, considere apoiar o projeto.",
      aboutDonateBtn: "Doar Agora",
      aboutContact: "Contato: goldpentakill@gmail.com",
      
      termsTitle: "Termos de Serviço",
      termsDesc: "Por favor, leia estes termos cuidadosamente antes de usar o Mythos Draft.",
      termsUpdated: "Última Atualização: Outubro de 2023",
      termsSec1Title: "1. Aceitação dos Termos",
      termsSec1Desc: "Ao acessar e usar o Mythos Draft, você aceita e concorda em ficar vinculado aos termos e disposições deste acordo.",
      termsSec2Title: "2. Uso Justo e Propriedade Intelectual",
      termsSec2Desc: "O Mythos Draft é uma ferramenta comunitária, sem fins lucrativos, feita por fãs. Age of Mythology: Retold e todos os ativos, personagens e nomes relacionados são propriedade intelectual da Microsoft Corporation. Esta ferramenta não reivindica propriedade sobre esses ativos e é fornecida sob uso justo para o benefício da comunidade.",
      termsSec3Title: "3. Conduta do Usuário",
      termsSec3Desc: "Os usuários concordam em usar o serviço com respeito. Abuso do sistema de draft, interrupção intencional de lobbies públicos ou exploração de bugs podem resultar no banimento da plataforma.",
      termsSec4Title: "4. Disponibilidade do Serviço",
      termsSec4Desc: "Nós nos esforçamos para 100% de tempo de atividade, especialmente durante grandes torneios, mas o Mythos Draft é fornecido \"como está\" sem garantias de qualquer tipo. Nós nos reservamos o direito de modificar ou descontinuar o serviço a qualquer momento.",
      termsSec5Title: "5. Integrações de Terceiros",
      termsSec5Desc: "Nosso serviço utiliza o Discord para autenticação durante torneios oficiais (Forja de Hefesto). Ao usar esses recursos, você também concorda com os Termos de Serviço do Discord.",

      privacyTitle: "Política de Privacidade",
      privacyDesc: "Como coletamos, usamos e protegemos seus dados.",
      privacyUpdated: "Última Atualização: Outubro de 2023",
      privacySec1Title: "1. Coleta de Dados",
      privacySec1Desc: "O Mythos Draft coleta dados pessoais mínimos. Para lobbies padrão, armazenamos apenas IDs de sessão temporários (Guest IDs) no seu navegador. Nenhuma informação pessoal identificável é necessária para usar a ferramenta de draft.",
      privacySec2Title: "2. Autenticação do Discord",
      privacySec2Desc: "Para recursos de torneios oficiais (ex: Forja de Hefesto), usamos o Discord OAuth. Só solicitamos seu ID do Discord, nome de usuário e avatar para verificar sua identidade. Não temos acesso a suas mensagens privadas, e-mail ou lista de amigos.",
      privacySec3Title: "3. Firebase e Banco de Dados",
      privacySec3Desc: "Nossa infraestrutura em tempo real é alimentada pelo Google Firebase. Dados do draft, incluindo nomes de jogadores e escolhas, são temporariamente armazenados para facilitar a sincronização ao vivo. Drafts concluídos podem ser arquivados para fins estatísticos.",
      privacySec4Title: "4. Compartilhamento de Dados",
      privacySec4Desc: "Não vendemos, trocamos ou alugamos suas informações de identificação pessoal. Estatísticas de draft e dados do meta podem ser compartilhados publicamente, mas esses dados são anonimizados.",
      privacySec5Title: "5. Seus Direitos",
      privacySec5Desc: "Você pode limpar seu armazenamento local a qualquer momento para remover seu Guest ID. Se você usou o Discord OAuth, pode revogar o acesso do Mythos Draft nas configurações de Aplicativos Autorizados do Discord.",

      cookiesTitle: "Política de Cookies",
      cookiesDesc: "Entendendo como usamos o armazenamento local para melhorar sua experiência.",
      cookiesUpdated: "Última Atualização: Outubro de 2023",
      cookiesSec1Title: "1. O que são Cookies?",
      cookiesSec1Desc: "Cookies e Armazenamento Local são pequenos pedaços de dados armazenados no seu dispositivo que ajudam os sites a lembrar informações sobre a sua visita. O Mythos Draft depende principalmente do Armazenamento Local (Local Storage).",
      cookiesSec2Title: "2. Armazenamento Essencial",
      cookiesSec2Desc: "Usamos Armazenamento Local estritamente necessário para gerenciar sua sessão. Isso inclui armazenar um `guestId` gerado para que o servidor reconheça você se atualizar a página acidentalmente durante um draft ativo.",
      cookiesSec3Title: "3. Preferências",
      cookiesSec3Desc: "Também podemos armazenar preferências simples localmente, como o idioma selecionado ou se você já aceitou nossas políticas.",
      cookiesSec4Title: "4. Rastreamento de Terceiros",
      cookiesSec4Desc: "Não usamos cookies invasivos de rastreamento de terceiros (como Google Analytics ou Meta Pixel) para fins publicitários. Sua atividade no Mythos Draft não é rastreada para anúncios.",

      consentTitle: "Nós valorizamos sua privacidade",
      consentDesc: "Usamos armazenamento local estritamente necessário para garantir o funcionamento do site. Não usamos cookies de publicidade ou rastreamento. Ao continuar usando o Mythos Draft, você concorda com o uso de armazenamento essencial.",
      consentLearnMore: "Saber Mais",
      consentAccept: "Aceitar",
      backToHome: "Voltar ao Início"
    }
  },
  es: {
    legal: {
      aboutTitle: "Sobre Mythos Draft",
      aboutDesc: "La principal herramienta de draft para la comunidad de Age of Mythology: Retold.",
      aboutProject: "El Proyecto",
      aboutProjectDesc: "Mythos Draft fue creado por pasión a la escena competitiva de Age of Mythology. Proporciona un entorno sincronizado en tiempo real para organizadores y jugadores.",
      aboutCreator: "El Creador",
      aboutCreatorDesc: "Desarrollado y mantenido por <strong class='text-white'>Kamarts</strong>. Este proyecto depende enormemente del feedback de la comunidad.",
      aboutMission: "Nuestra Misión",
      aboutMissionDesc: "Nuestro objetivo es elevar la experiencia competitiva proporcionando infraestructura impecable para drafts.",
      aboutDonate: "Apoya el Desarrollo",
      aboutDonateDesc: "Los costos de alojamiento y base de datos se acumulan. Considera donar para mantener el sitio sin anuncios.",
      aboutDonateBtn: "Donar Ahora",
      aboutContact: "Contacto: goldpentakill@gmail.com",
      
      termsTitle: "Términos de Servicio",
      termsDesc: "Lea estos términos cuidadosamente antes de usar Mythos Draft.",
      termsUpdated: "Última actualización: Octubre 2023",
      termsSec1Title: "1. Aceptación de los Términos",
      termsSec1Desc: "Al acceder y usar Mythos Draft, acepta estos términos.",
      termsSec2Title: "2. Uso Justo y Propiedad Intelectual",
      termsSec2Desc: "Mythos Draft es una herramienta de fans. Age of Mythology: Retold es propiedad de Microsoft Corporation.",
      termsSec3Title: "3. Conducta del Usuario",
      termsSec3Desc: "Los usuarios acuerdan usar el servicio con respeto. El abuso resultará en ban.",
      termsSec4Title: "4. Disponibilidad del Servicio",
      termsSec4Desc: "El servicio se proporciona 'tal cual' sin garantías de tiempo de actividad.",
      termsSec5Title: "5. Integraciones de Terceros",
      termsSec5Desc: "Usamos Discord para torneos oficiales. Al usarlo, acepta los términos de Discord.",

      privacyTitle: "Política de Privacidad",
      privacyDesc: "Cómo recopilamos y usamos sus datos.",
      privacyUpdated: "Última actualización: Octubre 2023",
      privacySec1Title: "1. Recolección de Datos",
      privacySec1Desc: "Recolectamos datos mínimos, principalmente IDs de sesión en su navegador.",
      privacySec2Title: "2. Autenticación de Discord",
      privacySec2Desc: "Solo pedimos ID de Discord, nombre de usuario y avatar para torneos.",
      privacySec3Title: "3. Base de Datos",
      privacySec3Desc: "Usamos Firebase. Los datos de drafts se almacenan temporalmente y pueden ser archivados para estadísticas.",
      privacySec4Title: "4. Compartir Datos",
      privacySec4Desc: "No vendemos sus datos. Las estadísticas son anonimizadas.",
      privacySec5Title: "5. Sus Derechos",
      privacySec5Desc: "Puede borrar el almacenamiento local en cualquier momento.",

      cookiesTitle: "Política de Cookies",
      cookiesDesc: "Entendiendo el uso del almacenamiento local.",
      cookiesUpdated: "Última actualización: Octubre 2023",
      cookiesSec1Title: "1. ¿Qué son?",
      cookiesSec1Desc: "Utilizamos principalmente Almacenamiento Local (Local Storage) en lugar de cookies tradicionales.",
      cookiesSec2Title: "2. Almacenamiento Esencial",
      cookiesSec2Desc: "Usamos almacenamiento local para manejar su sesión y evitar desconexiones.",
      cookiesSec3Title: "3. Preferencias",
      cookiesSec3Desc: "Guardamos sus preferencias de idioma.",
      cookiesSec4Title: "4. Sin Rastreo",
      cookiesSec4Desc: "No utilizamos cookies de rastreo ni publicidad.",

      consentTitle: "Valoramos su privacidad",
      consentDesc: "Usamos almacenamiento local estrictamente necesario. Al continuar, usted acepta su uso.",
      consentLearnMore: "Saber Más",
      consentAccept: "Aceptar",
      backToHome: "Volver al Inicio"
    }
  },
  fr: {
    legal: {
      aboutTitle: "À propos de Mythos Draft",
      aboutDesc: "Le principal outil de draft pour la communauté.",
      aboutProject: "Le Projet",
      aboutProjectDesc: "Créé par passion pour la scène compétitive de Age of Mythology.",
      aboutCreator: "Le Créateur",
      aboutCreatorDesc: "Développé et maintenu par <strong class='text-white'>Kamarts</strong>.",
      aboutMission: "Notre Mission",
      aboutMissionDesc: "Fournir une infrastructure professionnelle pour les drafts compétitifs.",
      aboutDonate: "Soutenir le Développement",
      aboutDonateDesc: "Aidez-nous à garder l'outil gratuit et rapide.",
      aboutDonateBtn: "Faire un don",
      aboutContact: "Contact: goldpentakill@gmail.com",
      
      termsTitle: "Conditions d'utilisation",
      termsDesc: "Veuillez lire attentivement.",
      termsUpdated: "Mis à jour: Octobre 2023",
      termsSec1Title: "1. Acceptation",
      termsSec1Desc: "En utilisant le site, vous acceptez ces termes.",
      termsSec2Title: "2. Propriété Intellectuelle",
      termsSec2Desc: "Outil créé par des fans. AoM est la propriété de Microsoft.",
      termsSec3Title: "3. Conduite",
      termsSec3Desc: "Tout abus entraînera un bannissement.",
      termsSec4Title: "4. Disponibilité",
      termsSec4Desc: "Le service est fourni 'tel quel'.",
      termsSec5Title: "5. Tiers",
      termsSec5Desc: "L'authentification Discord est requise pour les tournois.",

      privacyTitle: "Politique de Confidentialité",
      privacyDesc: "Protection de vos données.",
      privacyUpdated: "Mis à jour: Octobre 2023",
      privacySec1Title: "1. Collecte",
      privacySec1Desc: "Nous collectons un minimum de données (IDs de session).",
      privacySec2Title: "2. Discord",
      privacySec2Desc: "Nous n'accédons qu'aux informations publiques de base.",
      privacySec3Title: "3. Base de données",
      privacySec3Desc: "Les drafts sont stockés temporairement sur Firebase.",
      privacySec4Title: "4. Partage",
      privacySec4Desc: "Vos données personnelles ne sont jamais vendues.",
      privacySec5Title: "5. Droits",
      privacySec5Desc: "Vous pouvez vider votre cache à tout moment.",

      cookiesTitle: "Politique des Cookies",
      cookiesDesc: "Comment nous utilisons le stockage local.",
      cookiesUpdated: "Mis à jour: Octobre 2023",
      cookiesSec1Title: "1. Qu'est-ce que c'est ?",
      cookiesSec1Desc: "Nous utilisons le stockage local (Local Storage).",
      cookiesSec2Title: "2. Essentiel",
      cookiesSec2Desc: "Utilisé uniquement pour maintenir votre session active.",
      cookiesSec3Title: "3. Préférences",
      cookiesSec3Desc: "Stockage de la langue choisie.",
      cookiesSec4Title: "4. Pas de tracking",
      cookiesSec4Desc: "Aucun cookie publicitaire n'est utilisé.",

      consentTitle: "Confidentialité",
      consentDesc: "Nous utilisons un stockage local essentiel. En continuant, vous acceptez.",
      consentLearnMore: "En savoir plus",
      consentAccept: "Accepter",
      backToHome: "Retour à l'accueil"
    }
  },
  de: {
    legal: {
      aboutTitle: "Über Mythos Draft",
      aboutDesc: "Das führende Draft-Tool für die Community.",
      aboutProject: "Das Projekt",
      aboutProjectDesc: "Erstellt aus Leidenschaft für Age of Mythology.",
      aboutCreator: "Der Ersteller",
      aboutCreatorDesc: "Entwickelt von <strong class='text-white'>Kamarts</strong>.",
      aboutMission: "Unsere Mission",
      aboutMissionDesc: "Eine professionelle Infrastruktur für das kompetitive Spiel bieten.",
      aboutDonate: "Entwicklung unterstützen",
      aboutDonateDesc: "Helfen Sie uns, die Serverkosten zu decken.",
      aboutDonateBtn: "Jetzt spenden",
      aboutContact: "Kontakt: goldpentakill@gmail.com",
      
      termsTitle: "Nutzungsbedingungen",
      termsDesc: "Bitte aufmerksam lesen.",
      termsUpdated: "Stand: Oktober 2023",
      termsSec1Title: "1. Akzeptanz",
      termsSec1Desc: "Durch die Nutzung stimmen Sie diesen Bedingungen zu.",
      termsSec2Title: "2. Geistiges Eigentum",
      termsSec2Desc: "Ein Fan-Projekt. AoM gehört Microsoft.",
      termsSec3Title: "3. Verhalten",
      termsSec3Desc: "Missbrauch führt zum Ausschluss.",
      termsSec4Title: "4. Verfügbarkeit",
      termsSec4Desc: "Der Dienst wird 'wie besehen' bereitgestellt.",
      termsSec5Title: "5. Drittanbieter",
      termsSec5Desc: "Discord-Integration für offizielle Turniere.",

      privacyTitle: "Datenschutz",
      privacyDesc: "Wie wir Ihre Daten schützen.",
      privacyUpdated: "Stand: Oktober 2023",
      privacySec1Title: "1. Datenerhebung",
      privacySec1Desc: "Wir erheben nur minimale Sitzungsdaten.",
      privacySec2Title: "2. Discord",
      privacySec2Desc: "Nur öffentliche Profilinformationen werden abgerufen.",
      privacySec3Title: "3. Datenbank",
      privacySec3Desc: "Wir nutzen Firebase für die Echtzeit-Synchronisation.",
      privacySec4Title: "4. Weitergabe",
      privacySec4Desc: "Ihre Daten werden nicht verkauft.",
      privacySec5Title: "5. Ihre Rechte",
      privacySec5Desc: "Löschen Sie Ihren lokalen Speicher jederzeit.",

      cookiesTitle: "Cookie-Richtlinie",
      cookiesDesc: "Nutzung von lokalem Speicher.",
      cookiesUpdated: "Stand: Oktober 2023",
      cookiesSec1Title: "1. Was sind Cookies?",
      cookiesSec1Desc: "Wir verwenden hauptsächlich Local Storage.",
      cookiesSec2Title: "2. Essenziell",
      cookiesSec2Desc: "Wichtig für die Sitzungsverwaltung während des Drafts.",
      cookiesSec3Title: "3. Einstellungen",
      cookiesSec3Desc: "Speicherung der Sprachpräferenz.",
      cookiesSec4Title: "4. Kein Tracking",
      cookiesSec4Desc: "Wir nutzen keine Werbe-Tracker.",

      consentTitle: "Datenschutz",
      consentDesc: "Wir verwenden essenzielle Cookies/Speicher. Durch die Nutzung stimmen Sie zu.",
      consentLearnMore: "Mehr erfahren",
      consentAccept: "Akzeptieren",
      backToHome: "Zurück zur Startseite"
    }
  },
  ru: {
    legal: {
      aboutTitle: "О Mythos Draft",
      aboutDesc: "Лучший инструмент для драфта сообщества Age of Mythology.",
      aboutProject: "Проект",
      aboutProjectDesc: "Создан из страсти к соревновательной сцене.",
      aboutCreator: "Создатель",
      aboutCreatorDesc: "Разработано <strong class='text-white'>Kamarts</strong>.",
      aboutMission: "Наша Миссия",
      aboutMissionDesc: "Обеспечить профессиональную инфраструктуру для драфтов.",
      aboutDonate: "Поддержать разработку",
      aboutDonateDesc: "Помогите нам оплачивать серверы.",
      aboutDonateBtn: "Пожертвовать",
      aboutContact: "Контакт: goldpentakill@gmail.com",
      
      termsTitle: "Условия использования",
      termsDesc: "Пожалуйста, прочтите внимательно.",
      termsUpdated: "Обновлено: Октябрь 2023",
      termsSec1Title: "1. Принятие",
      termsSec1Desc: "Используя сайт, вы принимаете эти условия.",
      termsSec2Title: "2. Интеллектуальная собственность",
      termsSec2Desc: "Фанатский проект. AoM принадлежит Microsoft.",
      termsSec3Title: "3. Поведение",
      termsSec3Desc: "Злоупотребление приведет к бану.",
      termsSec4Title: "4. Доступность",
      termsSec4Desc: "Сервис предоставляется 'как есть'.",
      termsSec5Title: "5. Сторонние интеграции",
      termsSec5Desc: "Для турниров используется Discord.",

      privacyTitle: "Политика конфиденциальности",
      privacyDesc: "Защита ваших данных.",
      privacyUpdated: "Обновлено: Октябрь 2023",
      privacySec1Title: "1. Сбор данных",
      privacySec1Desc: "Мы собираем только минимальные данные сеанса.",
      privacySec2Title: "2. Discord",
      privacySec2Desc: "Только базовая информация профиля.",
      privacySec3Title: "3. База данных",
      privacySec3Desc: "Мы используем Firebase.",
      privacySec4Title: "4. Передача данных",
      privacySec4Desc: "Ваши данные не продаются.",
      privacySec5Title: "5. Ваши права",
      privacySec5Desc: "Вы можете очистить локальное хранилище в любое время.",

      cookiesTitle: "Политика файлов Cookie",
      cookiesDesc: "Использование локального хранилища.",
      cookiesUpdated: "Обновлено: Октябрь 2023",
      cookiesSec1Title: "1. Что это?",
      cookiesSec1Desc: "Мы используем Local Storage.",
      cookiesSec2Title: "2. Основные",
      cookiesSec2Desc: "Необходимо для сохранения сеанса при перезагрузке.",
      cookiesSec3Title: "3. Настройки",
      cookiesSec3Desc: "Сохранение языка.",
      cookiesSec4Title: "4. Без отслеживания",
      cookiesSec4Desc: "Мы не используем рекламные трекеры.",

      consentTitle: "Конфиденциальность",
      consentDesc: "Мы используем только необходимые данные. Продолжая, вы соглашаетесь.",
      consentLearnMore: "Подробнее",
      consentAccept: "Принять",
      backToHome: "На главную"
    }
  },
  da: {
    legal: {
      aboutTitle: "Om Mythos Draft",
      aboutDesc: "Det førende draft-værktøj til Age of Mythology.",
      aboutProject: "Projektet",
      aboutProjectDesc: "Skabt af passion for den kompetitive scene.",
      aboutCreator: "Skaberen",
      aboutCreatorDesc: "Udviklet af <strong class='text-white'>Kamarts</strong>.",
      aboutMission: "Vores Mission",
      aboutMissionDesc: "At levere en professionel infrastruktur til drafts.",
      aboutDonate: "Støt Udviklingen",
      aboutDonateDesc: "Hjælp os med at holde siden reklamefri.",
      aboutDonateBtn: "Doner Nu",
      aboutContact: "Kontakt: goldpentakill@gmail.com",
      
      termsTitle: "Betingelser",
      termsDesc: "Læs venligst grundigt.",
      termsUpdated: "Opdateret: Oktober 2023",
      termsSec1Title: "1. Accept",
      termsSec1Desc: "Ved brug accepterer du disse betingelser.",
      termsSec2Title: "2. Ophavsret",
      termsSec2Desc: "Et fan-projekt. AoM tilhører Microsoft.",
      termsSec3Title: "3. Adfærd",
      termsSec3Desc: "Misbrug medfører udelukkelse.",
      termsSec4Title: "4. Tilgængelighed",
      termsSec4Desc: "Tjenesten leveres 'som den er'.",
      termsSec5Title: "5. Tredjepart",
      termsSec5Desc: "Discord bruges til turneringer.",

      privacyTitle: "Privatlivspolitik",
      privacyDesc: "Beskyttelse af dine data.",
      privacyUpdated: "Opdateret: Oktober 2023",
      privacySec1Title: "1. Dataindsamling",
      privacySec1Desc: "Vi indsamler kun sessions-ID'er.",
      privacySec2Title: "2. Discord",
      privacySec2Desc: "Kun offentlig profilinformation.",
      privacySec3Title: "3. Database",
      privacySec3Desc: "Vi bruger Firebase.",
      privacySec4Title: "4. Deling",
      privacySec4Desc: "Dine data sælges ikke.",
      privacySec5Title: "5. Dine Rettigheder",
      privacySec5Desc: "Du kan rydde dit lokale lager til enhver tid.",

      cookiesTitle: "Cookie Politik",
      cookiesDesc: "Brug af lokalt lager.",
      cookiesUpdated: "Opdateret: Oktober 2023",
      cookiesSec1Title: "1. Hvad er det?",
      cookiesSec1Desc: "Vi bruger primært Local Storage.",
      cookiesSec2Title: "2. Nødvendige",
      cookiesSec2Desc: "Bruges til at håndtere din session.",
      cookiesSec3Title: "3. Præferencer",
      cookiesSec3Desc: "Gemmer dit valgte sprog.",
      cookiesSec4Title: "4. Ingen Tracking",
      cookiesSec4Desc: "Vi bruger ikke reklame-trackere.",

      consentTitle: "Privatliv",
      consentDesc: "Vi bruger kun nødvendigt lokalt lager. Ved at fortsætte accepterer du.",
      consentLearnMore: "Læs mere",
      consentAccept: "Accepter",
      backToHome: "Tilbage til forsiden"
    }
  },
  it: {
    legal: {
      aboutTitle: "Informazioni su Mythos Draft",
      aboutDesc: "Il miglior strumento di draft per Age of Mythology.",
      aboutProject: "Il Progetto",
      aboutProjectDesc: "Creato per passione della scena competitiva.",
      aboutCreator: "Il Creatore",
      aboutCreatorDesc: "Sviluppato da <strong class='text-white'>Kamarts</strong>.",
      aboutMission: "La Nostra Missione",
      aboutMissionDesc: "Fornire un'infrastruttura professionale per i draft.",
      aboutDonate: "Supporta lo Sviluppo",
      aboutDonateDesc: "Aiutaci a mantenere il sito senza pubblicità.",
      aboutDonateBtn: "Dona Ora",
      aboutContact: "Contatto: goldpentakill@gmail.com",
      
      termsTitle: "Termini di Servizio",
      termsDesc: "Si prega di leggere attentamente.",
      termsUpdated: "Aggiornato: Ottobre 2023",
      termsSec1Title: "1. Accettazione",
      termsSec1Desc: "Utilizzando il sito, accetti questi termini.",
      termsSec2Title: "2. Proprietà Intellettuale",
      termsSec2Desc: "Progetto fan-made. AoM appartiene a Microsoft.",
      termsSec3Title: "3. Comportamento",
      termsSec3Desc: "L'abuso comporterà il ban.",
      termsSec4Title: "4. Disponibilità",
      termsSec4Desc: "Il servizio è fornito 'così com'è'.",
      termsSec5Title: "5. Terze Parti",
      termsSec5Desc: "Discord è utilizzato per i tornei.",

      privacyTitle: "Politica sulla Privacy",
      privacyDesc: "Protezione dei tuoi dati.",
      privacyUpdated: "Aggiornato: Ottobre 2023",
      privacySec1Title: "1. Raccolta Dati",
      privacySec1Desc: "Raccogliamo solo ID di sessione minimi.",
      privacySec2Title: "2. Discord",
      privacySec2Desc: "Solo informazioni di profilo di base.",
      privacySec3Title: "3. Database",
      privacySec3Desc: "Utilizziamo Firebase.",
      privacySec4Title: "4. Condivisione",
      privacySec4Desc: "I tuoi dati non vengono venduti.",
      privacySec5Title: "5. I Tuoi Diritti",
      privacySec5Desc: "Puoi cancellare lo storage locale in qualsiasi momento.",

      cookiesTitle: "Politica sui Cookie",
      cookiesDesc: "Uso dello storage locale.",
      cookiesUpdated: "Aggiornato: Ottobre 2023",
      cookiesSec1Title: "1. Cosa sono?",
      cookiesSec1Desc: "Usiamo principalmente il Local Storage.",
      cookiesSec2Title: "2. Essenziali",
      cookiesSec2Desc: "Necessari per gestire la tua sessione.",
      cookiesSec3Title: "3. Preferenze",
      cookiesSec3Desc: "Salvataggio della lingua.",
      cookiesSec4Title: "4. Nessun Tracciamento",
      cookiesSec4Desc: "Non utilizziamo cookie pubblicitari.",

      consentTitle: "Privacy",
      consentDesc: "Usiamo solo storage locale essenziale. Continuando, accetti l'utilizzo.",
      consentLearnMore: "Scopri di più",
      consentAccept: "Accetta",
      backToHome: "Torna alla Home"
    }
  },
  mx: {
    legal: {
      aboutTitle: "Sobre Mythos Draft",
      aboutDesc: "La herramienta principal de draft para la comunidad LATAM.",
      aboutProject: "El Proyecto",
      aboutProjectDesc: "Creado por la pasión al Age of Mythology competitivo.",
      aboutCreator: "El Creador",
      aboutCreatorDesc: "Desarrollado por <strong class='text-white'>Kamarts</strong>.",
      aboutMission: "Nuestra Misión",
      aboutMissionDesc: "Brindar una infraestructura profesional para los drafts.",
      aboutDonate: "Apoya el Desarrollo",
      aboutDonateDesc: "Ayúdanos a mantener el sitio gratis y sin anuncios.",
      aboutDonateBtn: "Donar Ahora",
      aboutContact: "Contacto: goldpentakill@gmail.com",
      
      termsTitle: "Términos y Condiciones",
      termsDesc: "Por favor lee atentamente.",
      termsUpdated: "Actualizado: Octubre 2023",
      termsSec1Title: "1. Aceptación",
      termsSec1Desc: "Al usar el sitio, aceptas estos términos.",
      termsSec2Title: "2. Propiedad Intelectual",
      termsSec2Desc: "Proyecto de fans. AoM es de Microsoft.",
      termsSec3Title: "3. Conducta",
      termsSec3Desc: "El abuso del sistema resultará en un ban.",
      termsSec4Title: "4. Disponibilidad",
      termsSec4Desc: "El servicio se brinda 'tal cual'.",
      termsSec5Title: "5. Terceros",
      termsSec5Desc: "Usamos Discord para torneos oficiales.",

      privacyTitle: "Política de Privacidad",
      privacyDesc: "Protección de tus datos.",
      privacyUpdated: "Actualizado: Octubre 2023",
      privacySec1Title: "1. Recolección",
      privacySec1Desc: "Solo guardamos el ID de tu sesión temporal.",
      privacySec2Title: "2. Discord",
      privacySec2Desc: "Solo pedimos datos públicos para verificar identidad.",
      privacySec3Title: "3. Base de Datos",
      privacySec3Desc: "Usamos Firebase para los drafts en vivo.",
      privacySec4Title: "4. Compartir Datos",
      privacySec4Desc: "Nunca vendemos tu información personal.",
      privacySec5Title: "5. Tus Derechos",
      privacySec5Desc: "Puedes limpiar tu navegador cuando quieras.",

      cookiesTitle: "Política de Cookies",
      cookiesDesc: "Cómo usamos el almacenamiento local.",
      cookiesUpdated: "Actualizado: Octubre 2023",
      cookiesSec1Title: "1. ¿Qué son?",
      cookiesSec1Desc: "Usamos Local Storage, no cookies tradicionales.",
      cookiesSec2Title: "2. Esenciales",
      cookiesSec2Desc: "Sirven para que no te desconectes del draft.",
      cookiesSec3Title: "3. Preferencias",
      cookiesSec3Desc: "Guardamos tu idioma favorito.",
      cookiesSec4Title: "4. Sin Rastreo",
      cookiesSec4Desc: "No usamos rastreadores de publicidad.",

      consentTitle: "Privacidad",
      consentDesc: "Usamos almacenamiento local esencial para funcionar. Al seguir navegando, aceptas su uso.",
      consentLearnMore: "Saber Más",
      consentAccept: "Aceptar",
      backToHome: "Volver al Inicio"
    }
  }
};

const langs = Object.keys(translations);

for (const lang of langs) {
  const filePath = path.join(localesDir, `${lang}.json`);
  if (fs.existsSync(filePath)) {
    const data = fs.readFileSync(filePath, 'utf8');
    try {
      const json = JSON.parse(data);
      // Merging the new 'legal' block
      json.legal = translations[lang].legal;
      fs.writeFileSync(filePath, JSON.stringify(json, null, 2), 'utf8');
      console.log(`Updated ${lang}.json`);
    } catch (e) {
      console.error(`Error parsing ${lang}.json`, e);
    }
  }
}
